name: Build Push Changes
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Android SDK tools
        run: echo "$ANDROID_HOME/build-tools/30.0.3" >> $GITHUB_PATH

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Get short commit hash
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Mod Jar
        run: |
          chmod +x gradlew
          ./gradlew deploy

      - uses: actions/upload-artifact@v2
        with:
          name: Mod-Unzip-This
          path: build/tmp/deploy/*.jar

  release-draft:
    needs: build
    if: ${{ contains(github.event.head_commit.message,'[release]') }}
    runs-on: ubuntu-latest
    env:
      GH_REPO: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: Mod-Unzip-This
          path: out
      - name: Create Release Draft
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create new --draft out/*.jar